version = 1

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "21"
  language_version = "2.1"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "21"

[[code_formatters]]
name = "google-java-format"

[[code_formatters]]
name = "ktlint"